# Generated by Django 4.0 on 2021-12-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaworkapp', '0002_employee_role_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='instaworkapp_employee',
        ),
    ]
